export const currentFilePath = state => state.currentFilePath
export const filePaths = state => state.filePaths
export const previewHeight = state => state.previewHeight
export const wordCount = state => state.wordCount
export const favorite = state => state.favorite
export const searchState = state => state.searchState
export const searchWord = state => state.searchWord
export const mdDirectory = state => state.mdDirectory
export const mdDirectoryState = state => state.mdDirectoryState
export const viewportState = state => state.viewportState
export const textlintState = state => state.textlintState
